Repository mcanouil/quarto-extensions, pull requests merged in 2024-08, with the labels that each got.

#91 ci: case sensitivity issue in extensions retrieval
  .github/workflows/quarto-web.yml
Labels: Type: CI/CD :robot:

#92 ci: Check if there are new extensions before committing and pushing
  .github/workflows/quarto-web.yml
Labels: Type: CI/CD :robot:

#95 style: Add hover effect to author cards
  _quarto.yml
  assets/ejs/authors.ejs
  assets/stylesheets/authors.scss
Labels: Type: Enhancement :bulb:

#97 feat: add back to top button
  _quarto.yml
  assets/stylesheets/theme.scss
  authors.qmd
Labels: Type: Enhancement :bulb:

#99 feat: customise the EJS listing for extensions
  _quarto.yml
  assets/ejs/extensions.ejs
  assets/quarto/_author-listing.qmd
  assets/stylesheets/extensions.scss
  index.qmd
Labels: Type: Enhancement :bulb:

#102 feat: links are now highlited (coloured, underlined, and/or bold)
  assets/scripts/make-yaml.sh
  assets/stylesheets/theme.scss
Labels: Type: Enhancement :bulb:

#103 feat: copy button only on hover
  assets/stylesheets/theme.scss
Labels: Type: Enhancement :bulb:

#104 fix: hide counts in title metadata
  authors.qmd
  index.qmd
Labels: Type: Bug :bug:

#105 refactor: remove markdown in YAML content and improve search/filter
  _quarto.yml
  about.qmd
  assets/ejs/authors.ejs
  assets/ejs/extensions.ejs
  assets/quarto/_author-listing.qmd
  assets/scripts/current-year.html
  assets/scripts/make-yaml.sh
  assets/stylesheets/theme.scss
  index.qmd
Labels: Type: Refactor :fire:

#107 chore: Add wearetechnative/texnative
  extensions/quarto-extensions.csv
Labels: Type: Valorisation :tada:

#109 chore: add qmd-lab/closeread
  extensions/quarto-extensions.csv
Labels: Type: Valorisation :tada:

#111 ci: replace single quotes to allow bash variables
  .github/workflows/check-extensions.yml
Labels: Type: CI/CD :robot:

#110 chore: add edvinsyk/quarto-landscape extension
  extensions/quarto-extensions.csv
Labels: Type: Valorisation :tada:
