Repository mcanouil/quarto-extensions, pull requests merged in 2024-06, with the labels that each got.

#32 refactor: reduce api calls
  extensions/make-yaml.sh
Labels: Type: Refactor :fire:

#33 refactor: use repo view payload for topics
  extensions/make-yaml.sh
Labels: Type: Refactor :fire:

#34 fix: no topics in repo
  extensions/make-yaml.sh
Labels: Type: Bug :bug:

#35 deps: Update iconify to version 2.1.0
  _extensions/mcanouil/iconify/LICENSE
  _extensions/mcanouil/iconify/_extension.yml
  _extensions/mcanouil/iconify/iconify-icon.min.js
  _extensions/mcanouil/iconify/iconify.lua
Labels: Type: Dependencies :arrow_up:

#36 feat: Improve JS script and add stars, license, and switch to grid listing
  _quarto.yml
  extensions.qmd
  extensions/make-yaml.sh
Labels: Type: Enhancement :bulb:

#37 fix: description length and improve sorting
  extensions.qmd
  extensions/make-yaml.sh
Labels: Type: Bug :bug:

#38 style: tweak metadata and layout
  _quarto.yml
  assets/stylesheets/theme.scss
  extensions.qmd
  index.qmd
Labels: Type: Enhancement :bulb:

#40 ci: Add GitHub Actions for checking extensions
  .github/workflows/check-duplicate.yml
  .github/workflows/check-extensions.yml
Labels: Type: CI/CD :robot:

#41 chore: Add new Quarto extensions
  extensions/quarto-extensions.csv
Labels: Type: Valorisation :tada:

#44 chore: add pagiraud/fullframegraphics
  extensions/quarto-extensions.csv
Labels: Type: Valorisation :tada:

#46 chore: add scheduled-docs
  extensions/quarto-extensions.csv
Labels: Type: Valorisation :tada:
