Repository mcanouil/quarto-extensions, pull requests merged in 2024-04, with the labels that each got.

#11 feat: add extensions
  docs/extensions.html
  docs/index.html
  docs/search.json
  docs/site_libs/bootstrap/bootstrap.min.css
  docs/sitemap.xml
  extensions/quarto-extensions.csv
Labels: Type: Valorisation :tada:

#12 ci: update to deploy from GHA
  .github/workflows/deploy.yml
  .github/workflows/quarto-render.yml
  _quarto.yml
  docs/assets/media/quarto-extension.png
  docs/extensions.html
  docs/index.html
  docs/listings.json
  docs/robots.txt
  docs/search.json
  docs/site_libs/bootstrap/bootstrap-icons.css
  docs/site_libs/bootstrap/bootstrap-icons.woff
  docs/site_libs/bootstrap/bootstrap.min.css
  docs/site_libs/bootstrap/bootstrap.min.js
  docs/site_libs/clipboard/clipboard.min.js
  docs/site_libs/quarto-contrib/iconify-1.0.7/iconify-icon.min.js
  docs/site_libs/quarto-html/anchor.min.js
  docs/site_libs/quarto-html/popper.min.js
  docs/site_libs/quarto-html/quarto-syntax-highlighting.css
  docs/site_libs/quarto-html/quarto.js
  docs/site_libs/quarto-html/tippy.css
  docs/site_libs/quarto-html/tippy.umd.min.js
  docs/site_libs/quarto-listing/list.min.js
  docs/site_libs/quarto-listing/quarto-listing.js
  docs/site_libs/quarto-nav/headroom.min.js
  docs/site_libs/quarto-nav/quarto-nav.js
  docs/site_libs/quarto-search/autocomplete.umd.js
  docs/site_libs/quarto-search/fuse.min.js
  docs/site_libs/quarto-search/quarto-search.js
  docs/sitemap.xml
Labels: Type: CI/CD :robot:

#13 docs: remove proof of concept note
  README.md
  index.qmd
Labels: Type: Documentation :memo:

#14 feat: Add extensions
  .gitignore
  extensions/quarto-extensions.csv
Labels: Type: Valorisation :tada:

#20 ci: trigger on push for csv file
  .github/workflows/deploy.yml
Labels: Type: CI/CD :robot:

#19 Add gadenbuie/revealjs-text-resizer
  extensions/quarto-extensions.csv
Labels: Type: Valorisation :tada:
