Repository mcanouil/quarto-extensions, pull requests merged in 2025-04, with the labels that each got.

#154 feat: add support for fetching repository example content
  .github/workflows/quarto-wizard.yml
Labels: Type: Enhancement :bulb:

#155 feat: enable use template modal
  assets/ejs/extension-use-modal.ejs
Labels: Type: Enhancement :bulb:

#157 fix: modal display issue for multiple values
  assets/ejs/extension-install-modal.ejs
  assets/ejs/extension-use-modal.ejs
  assets/ejs/extensions.ejs
Labels: Type: Bug :bug:

#159 feat: enhance Quarto Wizard integration
  _quarto.yml
  about.qmd
  assets/ejs/extension-install-modal.ejs
  assets/ejs/extension-use-modal.ejs
  assets/media/quarto-wizard.svg
  assets/stylesheets/wizard.scss
Labels: Type: Enhancement :bulb:

#161 feat: add GitHub Actions workflow for testing Quarto extensions.
  .github/workflows/test-extensions.yml
Labels: Type: CI/CD :robot:

#162 chore: add code-appendix
  extensions/quarto-extensions.csv
Labels: Type: Valorisation :tada:

#164 feat: add placeholder image for missing social cards
  _quarto.yml
  assets/media/github-placeholder.png
  assets/scripts/make-yaml.sh
  index.qmd
Labels: Type: Enhancement :bulb:

#170 style: light and dark mode themes
  _quarto.yml
  assets/brand/dark.yml
  assets/brand/light.yml
  assets/ejs/extension-install-modal.ejs
  assets/ejs/extension-use-modal.ejs
  assets/scripts/make-yaml.sh
  assets/stylesheets/authors.scss
  assets/stylesheets/extensions.scss
  assets/stylesheets/theme.scss
Labels: Type: Enhancement :bulb:
