Repository mcanouil/quarto-extensions, pull requests merged in 2025-08, with the labels that each got.

#187 chore: update Iconify extension to version 3.0.1
  _extensions/mcanouil/iconify/_extension.yml
  _extensions/mcanouil/iconify/iconify.lua
Labels: Type: Dependencies :arrow_up:

#190 ci: refactor get extensions details workflow
  .github/workflows/quarto-wizard.yml
Labels: Type: CI/CD :robot:

#192 refactor: new listing interface
  README.md
  _quarto.yml
  about.qmd
  assets/brand/dark.yml
  assets/brand/light.yml
  assets/ejs/_controls.ejs
  assets/ejs/_grid.ejs
  assets/ejs/_list.ejs
  assets/ejs/_modal-install.ejs
  assets/ejs/_modal-use.ejs
  assets/ejs/authors.ejs
  assets/ejs/extensions.ejs
  assets/ejs/listing.ejs
  assets/scripts/categories-alphabetical.html
  assets/scripts/make-listings.sh
  assets/scripts/quarto-extensions-listing.html
  assets/stylesheets/authors.scss
  assets/stylesheets/extensions.scss
  assets/stylesheets/theme.scss
  authors.qmd
  index.qmd
Labels: Type: Refactor :fire:

#194 fix: remove page title from extensions listing page
  index.qmd
Labels: Type: Enhancement :bulb:

#198 chore: add EmilHvitfeldt/quarto-revealjs-imagemover
  extensions/quarto-extensions.csv
Labels: Type: Valorisation :tada:

#200 chore: add quarto-output-styling extension
  extensions/quarto-extensions.csv
Labels: Type: Valorisation :tada:

#206 feat: Extend search to include user/organisation names
  assets/scripts/quarto-extensions-listing.html
Labels: Type: Enhancement :bulb:
